/**
 * AUTO-GENERATED STUB — Replace with real Convex codegen after `npx convex dev`
 * 
 * This file provides type stubs for development before Convex deployment.
 */

import type { FunctionReference } from "convex/server";

// Stub type for API references
type ApiStub = {
  [module: string]: {
    [fn: string]: FunctionReference<any, any, any, any>;
  };
};

/**
 * API reference object — maps to Convex functions
 * Real implementation auto-generated by Convex CLI
 */
export const api: ApiStub = {
  // Retailers module
  retailers: {
    list: {} as any,
    get: {} as any,
    getBySlug: {} as any,
    create: {} as any,
    update: {} as any,
    updateScrapeStatus: {} as any,
    listByRegion: {} as any,
    getScrapeDue: {} as any,
  },
  
  // Brands module
  brands: {
    list: {} as any,
    get: {} as any,
    getByNormalizedName: {} as any,
    create: {} as any,
    update: {} as any,
    search: {} as any,
    addAlias: {} as any,
  },
  
  // Products module
  products: {
    list: {} as any,
    get: {} as any,
    getByBrand: {} as any,
    search: {} as any,
    create: {} as any,
    update: {} as any,
    getByCategory: {} as any,
  },
  
  // Inventory module
  inventory: {
    getCurrentByRetailer: {} as any,
    getCurrentByProduct: {} as any,
    getCurrentByBrand: {} as any,
    getStockStatus: {} as any,
    getPriceHistory: {} as any,
  },
  
  // Analytics module
  analytics: {
    getBrandAnalytics: {} as any,
    getMarketOverview: {} as any,
    getRegionStats: {} as any,
    computeDailyAnalytics: {} as any,
  },
  
  // Ingestion module
  ingestion: {
    ingestScrapedBatch: {} as any,
  },
};

/**
 * Internal function references — for scheduler, cron, internal calls
 */
export const internal: ApiStub = {
  analytics: {
    computeDailyAnalytics: {} as any,
  },
  ingestion: {
    processNormalization: {} as any,
  },
};
